defaultAirflowTag: "2.5.0"
airflowVersion: "2.5.0"
executor: "KubernetesExecutor"

extraEnvFrom: |
  - configMapRef:
      name: 'airflow-variables'

scheduler:
  replicas: 2

webserver:
  replicas: 2
  defaultUser:
    enabled: true
    role: Admin
    username: giovanni.gomes
    email: giovannigomes.snt@gmail.com
    firstName: Giovanni
    lastName: Leocadio
    password: admin
  service:
    type: LoadBalancer

redis:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/giovannigomesgt/ETLGOV.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    wait: 15
    containerName: git-sync
    uid: 65533
    securityContext: {}
    extraVolumeMounts: []
    env: []
    resources: {}