defaultAirflowTag: "2.5.0"
airflowVersion: "2.5.0"


workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 3

scheduler:
  replicas: 2

webserver:
  replicas: 2
  defaultUser:
    enabled: true
    role: Admin
    username: giovanni.gomes
    email: giovannigomes.snt@gmail.com
    firstName: Giovanni
    lastName: Leocadio
    password: admin
  service:
    type: LoadBalancer

triggerer:
  replicas: 1

# redis:
#   enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/giovannigomesgt/ETLGOV.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    wait: 15
    containerName: git-sync
    uid: 65533